FileVersion = 1

[Project]
Name = "ulid-beef"
DefaultNamespace = "ulid"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\ulid_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\ulid.lib"]